//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelSistemi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        public int PersonelID { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> IseGirisTarih { get; set; }
        public Nullable<System.DateTime> IstenCikisTarih { get; set; }
        public Nullable<int> Departman { get; set; }
        public Nullable<int> Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual Tbl_Departman Tbl_Departman { get; set; }
        public virtual Tbl_Durum Tbl_Durum { get; set; }
        public virtual Tbl_Gorev Tbl_Gorev { get; set; }
    }
}
