//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelSistemi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> UrunGrup { get; set; }
        public Nullable<int> Birim { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<byte> Kdv { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual Tbl_Birim Tbl_Birim { get; set; }
        public virtual Tbl_Durum Tbl_Durum { get; set; }
        public virtual Tbl_UrunGrup Tbl_UrunGrup { get; set; }
    }
}
